print('CALCULADORA AMBULANTE')
n1=int(input('Digite um número:'))
n2=int(input('Digite outro:'))
print('SOMA={}'.format(n1+n2))
print('SUBTRAÇÃO={}'.format(n1-n2))
print('MULTIPLICAÇÃO={}'.format(n1*n2))
print('DIVISÃO={}'.format(n1/n2))
print('EXPONENCIAL={}'.format(n1**n2))
print('DIVISÃO INTEIRA={}'.format(n1//n2))
